package com.github.trueddd.theme

import androidx.compose.ui.graphics.Color

val md_theme_dark_primary = Color(0xFFE6B4FF)
val md_theme_dark_onPrimary = Color(0xFF491765)
val md_theme_dark_primaryContainer = Color(0xFF62317E)
val md_theme_dark_onPrimaryContainer = Color(0xFFF5D9FF)
val md_theme_dark_secondary = Color(0xFFD3C0D8)
val md_theme_dark_onSecondary = Color(0xFF382C3E)
val md_theme_dark_secondaryContainer = Color(0xFF4F4255)
val md_theme_dark_onSecondaryContainer = Color(0xFFF0DCF4)
val md_theme_dark_tertiary = Color(0xFFF4B7B7)
val md_theme_dark_onTertiary = Color(0xFF4C2526)
val md_theme_dark_tertiaryContainer = Color(0xFF663B3C)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDAD9)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1D1B1E)
val md_theme_dark_onBackground = Color(0xFFE8E0E5)
val md_theme_dark_surface = Color(0xFF1D1B1E)
val md_theme_dark_onSurface = Color(0xFFE8E0E5)
val md_theme_dark_surfaceVariant = Color(0xFF4B444D)
val md_theme_dark_onSurfaceVariant = Color(0xFFCEC3CE)
val md_theme_dark_outline = Color(0xFF978E98)
val md_theme_dark_inverseOnSurface = Color(0xFF1D1B1E)
val md_theme_dark_inverseSurface = Color(0xFFE8E0E5)
val md_theme_dark_inversePrimary = Color(0xFF7B4997)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFE6B4FF)
val md_theme_dark_outlineVariant = Color(0xFF4B444D)
val md_theme_dark_scrim = Color(0xFF000000)

val seed = Color(0xFF5F2E7B)
val Success = Color(0xFF4ADE80)
val Error = Color(0xFFF87171)
val light_Success = Color(0xFF006D36)
val light_onSuccess = Color(0xFFFFFFFF)
val light_SuccessContainer = Color(0xFF6DFE9C)
val light_onSuccessContainer = Color(0xFF00210C)
val dark_Success = Color(0xFF4DE082)
val dark_onSuccess = Color(0xFF003919)
val dark_SuccessContainer = Color(0xFF005227)
val dark_onSuccessContainer = Color(0xFF6DFE9C)
val light_Error = Color(0xFFA83639)
val light_onError = Color(0xFFFFFFFF)
val light_ErrorContainer = Color(0xFFFFDAD8)
val light_onErrorContainer = Color(0xFF410006)
val dark_Error = Color(0xFFFFB3B0)
val dark_onError = Color(0xFF670211)
val dark_ErrorContainer = Color(0xFF881D24)
val dark_onErrorContainer = Color(0xFFFFDAD8)
