name: Checks

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: assemble
    - name: Run tests
      uses: gradle/gradle-build-action@v2
      with:
        arguments: test --info
    - name: Test report
      if: success() || failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: ./backend/build/reports/tests/jvmTest
